### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/mopidy/jellyfin/token'

### ISSUE THREAD

**Issue by arthurlutz** [jellyfin/mopidy-jellyfin#69]
```
2020-07-06 19:23:41,877 ERROR [7363:MainThread] mopidy.commands: Got un-handled exception from EventMonitorFrontend
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/commands.py", line 241, in _actor_error_handling
    yield
  File "/usr/local/lib/python3.7/dist-packages/mopidy/commands.py", line 438, in start_frontends
    frontend_class.start(config=config, core=core)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 91, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_jellyfin/frontend.py", line 23, in __init__
    self.token = self._read_token(config)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_jellyfin/frontend.py", line 222, in _read_token
    with open(token_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/mopidy/jellyfin/token'
```

**Comment by mcarlton00** [comment]
Cause is #70, closing

**Comment by arthurlutz** [comment]
I think it would be nice to catch this traceback and display an error instead.
